import Head from 'next/head'
import { useAuth, useAuthActions } from 'src/context/AuthContext';

export default function Home() {
  const { user } = useAuth()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen'>
        <div className='p-6'>
          <h1 className='text-3xl font-black'>سلام {user ? user.name : ''} به Next-App خوش آمدی</h1>
        </div>
      </main>
    </>
  )
}
